AWSTemplateFormatVersion: 2010-09-09
Parameters:
  LatestAMI:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      UserData: !Base64 
        Ref: myWaitHandle
      ImageId: !Ref LatestAMI
      InstanceType: t2.micro
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 5d105b8b-5aea-4a6d-aad3-928a5c820fb6
  myWaitHandle:
    Type: 'AWS::CloudFormation::WaitConditionHandle'
    Properties: {}
    Metadata:
      'AWS::CloudFormation::Designer':
        id: e17cad75-f9e7-46bf-b181-4e8c94176df4
  myWaitCondition:
    Type: 'AWS::CloudFormation::WaitCondition'
    DependsOn: Ec2Instance
    Properties:
      Handle: !Ref myWaitHandle
      Timeout: '4500'
    Metadata:
      'AWS::CloudFormation::Designer':
        id: d09bfb94-92eb-41e1-9f45-556b02d5bd46
Outputs:
  ApplicationData:
    Value: !GetAtt 
      - myWaitCondition
      - Data
    Description: The data passed back as part of signalling the WaitCondition.

